# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Projects\ImageMatchAnnotator\Registration\win.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from vtkWidget.vtkWidget import VtkWidget


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setGeometry(QtCore.QRect(10, 10, 161, 161))
        self.widget_2.setStyleSheet("background-color: rgba(255, 255, 255, 100);")
        self.widget_2.setObjectName("widget_2")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.widget_2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 160, 161))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.LoadDirButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.LoadDirButton.setObjectName("LoadDirButton")
        self.verticalLayout.addWidget(self.LoadDirButton)
        self.frameScrollBar = QtWidgets.QScrollBar(self.verticalLayoutWidget)
        self.frameScrollBar.setOrientation(QtCore.Qt.Horizontal)
        self.frameScrollBar.setObjectName("frameScrollBar")
        self.verticalLayout.addWidget(self.frameScrollBar)
        self.addKeyframeButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.addKeyframeButton.setObjectName("addKeyframeButton")
        self.verticalLayout.addWidget(self.addKeyframeButton)
        self.progressBar = QtWidgets.QProgressBar(self.verticalLayoutWidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.resetButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.resetButton.setObjectName("resetButton")
        self.verticalLayout.addWidget(self.resetButton)
        self.arCheckBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.arCheckBox.setObjectName("arCheckBox")
        self.verticalLayout.addWidget(self.arCheckBox)
        self.vtkWidget = VtkWidget(self.centralwidget)
        self.vtkWidget.setGeometry(QtCore.QRect(0, 0, 1920, 1080))
        self.vtkWidget.setObjectName("vtkWidget")
        self.vtkWidget.lower()
        self.verticalLayoutWidget.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.LoadDirButton.setText(_translate("MainWindow", "Load Dir"))
        self.addKeyframeButton.setText(_translate("MainWindow", "Add Keyframe"))
        self.resetButton.setText(_translate("MainWindow", "Reset"))
        self.arCheckBox.setText(_translate("MainWindow", "AR"))
